In [9]:
n=3

In [11]:
G = SymmetricGroup(n)

In [56]:
SGA = G.algebra(QQ)

In [57]:
A = SGA.dft(); A

[   1    1    1    1    1    1]
[   1 -1/2 -1/2  1/2  1/2   -1]
[   0 -3/4  3/4  3/4 -3/4    0]
[   0    1   -1    1   -1    0]
[   1 -1/2 -1/2 -1/2 -1/2    1]
[   1    1    1   -1   -1   -1]

In [89]:
#is the matrix unitary?
#A*A^T is diagonal, but not the identity. so A is not unitary.
#A*A^T is called the Gram matrix

In [58]:
print((A*A.transpose()).str())

[  6   0   0   0   0   0]
[  0   3   0   0   0   0]
[  0   0 9/4   0   0   0]
[  0   0   0   4   0   0]
[  0   0   0   0   3   0]
[  0   0   0   0   0   6]


In [3]:
#define a new DFT which is unitary

In [71]:
#define the Fourier coefficient at the representation spc
#which is the Specht module corresponding to partition
def f_hat(f,partition):
    specht_module = SGA.specht_module(partition)
    d_part = specht_module.dimension()
    return sqrt(d_part/factorial(n))*sum(f(sigma)*specht_module.representation_matrix(sigma) for sigma in G)

In [24]:
#define the delta function delta_\s(\t) = {1 if s == t, 0 otherwise}
def delta(s):
    return lambda t: 1 if t == s else 0

In [45]:
#compute \hat{\delta_s}(partition) for each basis vector s \in G
from sage.misc.flatten import flatten
def unitary_dft():
    return matrix([flatten([f_hat(delta(g),partition).list() for partition in Partitions(n)]) for g in G]).transpose()

In [72]:
unitary_dft()*unitary

[ sqrt(1/6)  sqrt(1/6)  sqrt(1/6)  sqrt(1/6)  sqrt(1/6)  sqrt(1/6)]
[ sqrt(1/3) -sqrt(1/3)          0 -sqrt(1/3)          0  sqrt(1/3)]
[         0  sqrt(1/3) -sqrt(1/3)          0  sqrt(1/3) -sqrt(1/3)]
[         0 -sqrt(1/3)  sqrt(1/3) -sqrt(1/3)  sqrt(1/3)          0]
[ sqrt(1/3)          0 -sqrt(1/3)  sqrt(1/3)          0 -sqrt(1/3)]
[ sqrt(1/6)  sqrt(1/6)  sqrt(1/6) -sqrt(1/6) -sqrt(1/6) -sqrt(1/6)]

In [61]:
SGA.specht_module(Partitions(n)[1]).representation_matrix(G[1])

[-1  1]
[-1  0]

In [58]:
#what are the eigenvalues?
#n=3: two real, two complex
#n=4: all complex
#the magnitude is not 1, they're closely grouped around 2 or 3

In [92]:
eigs = A.eigenvalues(); eigs

[-1.927382440195288?, 2.121715010353017?, -1.174423554578382? - 1.623003052198150?*I, -1.174423554578382? + 1.623003052198150?*I, 1.452257269499517? - 1.086817272076326?*I, 1.452257269499517? + 1.086817272076326?*I]

In [93]:
[abs(eig) for eig in eigs]

[1.927382440195288?,
 2.121715010353017?,
 2.003349593304431?,
 2.003349593304431?,
 1.813897174510622?,
 1.813897174510622?]

In [121]:
#note that the singluar values are the square roots of the diagonal entries of the Gram matrix
print(SymmetricGroup(n).algebra(CDF).dft().SVD()[1].numpy().diagonal())
print(sqrt((A*A.transpose()).numpy().diagonal()))

[2.44948974+0.j 2.44948974+0.j 2.        +0.j 1.73205081+0.j
 1.73205081+0.j 1.5       +0.j]
[2.44948974 1.73205081 1.5        2.         1.73205081 2.44948974]
