In [37]:
#define a new DFT which is unitary
#NOTE: in Beals' ['97] he normalizes by \sqrt{d_\lambda/n!}
#but also notes that a basis change is an equivalence relation on rep'ns
#and each equivalence class contains a unitary representatione
#if each rep'n \rho \in \hat{G} is unitary, then the transformation is unitary
#these representations are not unitary
#to make them unitary, use Weyl's unitary trick
#OPTION 1: use the formula P = \int_G \rho(g)\rho(g)^* dg, and take a square root to find Q s.t. P = Q^2
#OPTION 2: define a new invariant inner product compute an orthonormal basis w.r.t. 
#this inner product by computing the Gram matrix A and using A.gram_schmidt()

In [38]:
#compute a field which contains all the square roots required
def containing_field(SGA):
    required_square_roots = []
    for partition in Partitions(SGA.group().degree()):
        specht_module = SGA.specht_module(partition)
        rho = specht_module.representation_matrix
        group_size = SGA.group().cardinality()
        P = (1/group_size)*sum(rho(g)*rho(g).conjugate().transpose() for g in SGA.group())
        d, L = P.eigenmatrix_left()
        required_square_roots += [specht_module.dimension(),SGA.group().cardinality()] + d.diagonal()
    required_square_roots = flatten([[QQ(q).numerator(),QQ(q).denominator()] if q in QQ else q for q in required_square_roots])
    K = SGA.base_ring()
    for n in set(required_square_roots):
        R = PolynomialRing(K, 'x')
        x = R.gen()
        if (x**2 - n).is_irreducible():
            gen_name = "sqrt"+str(n).replace("/","over")
            K = K.extension(sqrt(n).minpoly(),names=gen_name)
    return K

In [39]:
#find the change-of-basis matrix Q making \rho(g) unitary for all g \in G
from sage.matrix.special import diagonal_matrix
from sage.misc.functional import sqrt
def unitary_change_of_basis(SGA,partition,K):
    rho = SGA.specht_module(partition).representation_matrix
    group_size = SGA.group().cardinality()
    P = (1/group_size)*sum(rho(g)*rho(g).conjugate().transpose() for g in SGA.group())
    d, L = P.eigenmatrix_left()
    return L.inverse() * diagonal_matrix([sqrt(K(a)) for a in d.diagonal()]) * L

In [40]:
#define the Fourier coefficient at the representation specht_module
#which is the Specht module corresponding to partition
def hat(f,partition,SGA,K,unitary=False):
    specht_module = SGA.specht_module(partition)
    rho = specht_module.representation_matrix
    if unitary:
        Q = unitary_change_of_basis(SGA,partition,K)
        unitary_factor = specht_module.dimension()/SGA.group().cardinality()
        sqrt_unitary_factor = sqrt(K(unitary_factor))
        return sqrt_unitary_factor*sum(f(g)*Q.inverse()*rho(g)*Q for g in SGA.group())
    else:
        return sum(f(g)*rho(g) for g in SGA.group())

In [41]:
#define the delta function delta_s(t) = {1 if s == t, 0 otherwise}
delta = lambda s: lambda t: 1 if t == s else 0

In [42]:
#for each basis element g \in G compute the Fourier coefficients \hat{\delta_g}(partition) for all partitions
from sage.misc.flatten import flatten
def unitary_dft(SGA):
    K = containing_field(SGA)
    return matrix(K,[flatten([hat(delta(g),partition,SGA,K,unitary=True).list() for partition in Partitions(SGA.group().degree())]) for g in SGA.group()]).transpose()

In [43]:
n = 3

In [44]:
SGA = SymmetricGroupAlgebra(QQbar,n)

In [45]:
K = containing_field(SGA); K

Algebraic Field

In [46]:
G = SGA.group()

In [47]:
SGA_dft = SGA.dft(); SGA_dft

[   1    1    1    1    1    1]
[   1  1/2   -1 -1/2 -1/2  1/2]
[   0  3/4    0  3/4 -3/4 -3/4]
[   0    1    0   -1    1   -1]
[   1 -1/2    1 -1/2 -1/2 -1/2]
[   1   -1   -1    1    1   -1]

In [48]:
#check if A*A^T == Id. it's not, but the columns are orthonormal
SGA_dft*SGA_dft.transpose()

[  6   0   0   0   0   0]
[  0   3   0   0   0   0]
[  0   0 9/4   0   0   0]
[  0   0   0   4   0   0]
[  0   0   0   0   3   0]
[  0   0   0   0   0   6]

In [49]:
partition = Partitions(SGA.group().degree())[1]; partition

[2, 1]

In [50]:
specht_module = SGA.specht_module(partition)

In [51]:
rho = specht_module.representation_matrix

In [52]:
group_size = SGA.group().cardinality()

In [53]:
P = (1/group_size)*sum(rho(g)*rho(g).conjugate().transpose() for g in SGA.group()); P.base_ring()

Algebraic Field

In [54]:
Q = unitary_change_of_basis(SGA,partition,K); Q

[ 1.115355071650411? 0.2988584907226845?]
[0.2988584907226845?  1.115355071650411?]

In [55]:
unitary_factor = specht_module.dimension()/SGA.group().cardinality(); unitary_factor

1/3

In [56]:
K

Algebraic Field

In [57]:
G[3]

[2, 3, 1]

In [58]:
U_rho = Q.inverse()*rho(G[3])*Q; U_rho

[-0.500000000000000?  0.866025403784439?]
[-0.866025403784439? -0.500000000000000?]

In [59]:
U_rho*U_rho.conjugate().transpose()

[1.000000000000000?            0.?e-17]
[           0.?e-17 1.000000000000000?]

In [60]:
unitary_dft(SGA)

[ 0.4082482904638630?  0.4082482904638630?  0.4082482904638630?  0.4082482904638630?  0.4082482904638630?  0.4082482904638630?]
[ 0.5773502691896258?                    0   0.500000000000000? -0.2886751345948129? -0.2886751345948129?  -0.500000000000000?]
[             0.?e-18  0.5773502691896258? -0.2886751345948129?   0.500000000000000?  -0.500000000000000? -0.2886751345948129?]
[             0.?e-18  0.5773502691896258? -0.2886751345948129?  -0.500000000000000?   0.500000000000000? -0.2886751345948129?]
[ 0.5773502691896258?                    0  -0.500000000000000? -0.2886751345948129? -0.2886751345948129?   0.500000000000000?]
[ 0.4082482904638630? -0.4082482904638630? -0.4082482904638630?  0.4082482904638630?  0.4082482904638630? -0.4082482904638630?]

In [61]:
U_dft = unitary_dft(SGA); U_dft*U_dft.conjugate().transpose()

[1.000000000000000?            0.?e-18            0.?e-18            0.?e-18            0.?e-18            0.?e-18]
[           0.?e-18 1.000000000000000?            0.?e-18            0.?e-18            0.?e-18            0.?e-18]
[           0.?e-18            0.?e-18 1.000000000000000?            0.?e-18            0.?e-18            0.?e-18]
[           0.?e-18            0.?e-18            0.?e-18 1.000000000000000?            0.?e-18            0.?e-18]
[           0.?e-18            0.?e-18            0.?e-18            0.?e-18 1.000000000000000?            0.?e-18]
[           0.?e-18            0.?e-18            0.?e-18            0.?e-18            0.?e-18 1.000000000000000?]

In [62]:
#check that the DFT is unitary
(U_dft*U_dft.transpose()) == identity_matrix(SGA.group().cardinality())

True

In [63]:
#QUESTION: what are the eigenvalues?
#need to be careful as characteristic polynomial is degree n! over K, so [L:QQ] = [L:K]*[K:QQ] = n!*[K:QQ]
#for n=3, [L:QQ] = n!*[K:QQ] = 6*4 = 24

In [64]:
U_dft.charpoly()

x^6 + 1.0773502691897?*x^5 - 0.924311009994?*x^4 - 2.10095363131?*x^3 - 0.92431101000?*x^2 + 1.077350269190?*x + 1.00000000000?

In [65]:
#ISSUE: the splitting field appears to be high degree, and the coefficients are large
#the defining polynomial is monic with integer coefficients
#since the eigenvalues lie on the unit circle, a result of Kroenecker implies they are roots of unity
if len(list(U_dft.charpoly().factor())) != U_dft.charpoly().degree():
    L.<a> = U_dft.charpoly().splitting_field(); L
else:
    L = K

In [66]:
L

Algebraic Field

In [67]:
#one can factor the polynomial over a splitting field L/K
#but there is no way to express the roots of a quintic in terms of radicals
eigs = matrix(L,U_dft).eigenvalues(extend=False); eigs

[-0.9865699009578278? - 0.1633396171296542?*I, -0.9865699009578278? + 0.1633396171296542?*I, -0.5437444089082021? - 0.8392508670124029?*I, -0.5437444089082021? + 0.8392508670124029?*I, 0.9916391752712170? - 0.1290416447020912?*I, 0.9916391752712170? + 0.1290416447020912?*I]

In [140]:
(arg(eigs[0])/(2*pi)).n(100)

-0.47388668606429877463829835272

In [88]:
(arg(eigs[0])/(2*pi)).n(1_000_000).nearby_rational(max_denominator=100_000_000_000_000_000_000_000_000_000_000_000_000_000)

-22539521630051773595348404504870938475879/47563103781720350556946374220559905473074

In [84]:
eigs[0].imag()/eigs[0].real()

0.1655631465860383?

In [70]:
rational_approx_args = [(arg(eig)/(2*pi)).n(100).nearby_rational(max_denominator=100_000_000_000_000_000_000_000) for eig in eigs]; rational_approx_args

[-10782678805850241855303/22753706999878039149494,
 10782678805850241855303/22753706999878039149494,
 -19751357844255063647819/57837581692632446111637,
 19751357844255063647819/57837581692632446111637,
 -229510577551663428287/11143970750595710312210,
 229510577551663428287/11143970750595710312210]

In [71]:
prod([x-exp(2*pi*I*q).n() for q in rational_approx_args]).expand()

x^6 + 1.07735026918963*x^5 - (0.924311009993415 + 1.11022302462516e-16*I)*x^4 - 2.10095363130390*x^3 - (0.924311009993415 - 2.22044604925031e-16*I)*x^2 + (1.07735026918963 + 2.22044604925031e-16*I)*x + 1.00000000000000

In [72]:
#galois_group() appears to be the absolute version
#NOTE: for a splitting field L, we should have [L:K] = |Gal(L/K)|
if L != L.algebraic_closure():
    L_G = L.galois_group()

In [73]:
#n=3: two real, two complex
#n=4: all complex
#the magnitude is not 1, they're closely grouped around 2 or 3

In [74]:
SGA_eigs = SGA_dft.eigenvalues(); SGA_eigs

[2.203130118946493?, 0.6196927916815408? + 1.649489291766649?*I, 0.6196927916815408? - 1.649489291766649?*I, -1.180831595337157? + 1.549010082939973?*I, -1.180831595337157? - 1.549010082939973?*I, -2.080852511635262?]

In [75]:
[abs(eig) for eig in SGA_eigs]

[2.203130118946493?,
 1.762053937799550?,
 1.762053937799550?,
 1.947766796512405?,
 1.947766796512405?,
 2.080852511635262?]

In [76]:
#note that the singluar values are the square roots of the diagonal entries of the Gram matrix
print(SymmetricGroup(n).algebra(CDF).dft().SVD()[1].numpy().diagonal())
print(sqrt((SGA_dft*SGA_dft.transpose()).numpy().diagonal()))

[2.44948974+0.j 2.44948974+0.j 2.        +0.j 1.73205081+0.j
 1.73205081+0.j 1.5       +0.j]
[2.449489742783178? 1.732050807568878? 3/2 2 1.732050807568878?
 2.449489742783178?]
