In [47]:
#define a new DFT which is unitary
#NOTE: in Beals' ['97] he normalizes by \sqrt{d_\lambda/n!}
#but also notes that a basis change is an equivalence relation on rep'ns
#and each equivalence class contains a unitary representatione
#if each rep'n \rho \in \hat{G} is unitary, then the transformation is unitary
#these representations are not unitary
#to make them unitary, use Weyl's unitary trick
#OPTION 1: use the formula P = \int_G \rho(g)\rho(g)^* dg, and take a square root to find Q s.t. P = Q^2
#OPTION 2: define a new invariant inner product compute an orthonormal basis w.r.t. 
#this inner product by computing the Gram matrix A and using A.gram_schmidt()

In [48]:
#compute a field which contains all the square roots required
def containing_field(SGA):
    required_square_roots = []
    for partition in Partitions(SGA.group().degree()):
        specht_module = SGA.specht_module(partition)
        rho = specht_module.representation_matrix
        group_size = SGA.group().cardinality()
        P = (1/group_size)*sum(rho(g)*rho(g).conjugate().transpose() for g in SGA.group())
        d, L = P.eigenmatrix_left()
        required_square_roots += [specht_module.dimension(),SGA.group().cardinality()] + d.diagonal()
    required_square_roots = flatten([[QQ(q).numerator(),QQ(q).denominator()] if q in QQ else q for q in required_square_roots])
    K = SGA.base_ring()
    for n in set(required_square_roots):
        R = PolynomialRing(K, 'x')
        x = R.gen()
        if (x**2 - n).is_irreducible():
            gen_name = "sqrt"+str(n).replace("/","over")
            K = K.extension(sqrt(n).minpoly(),names=gen_name)
    return K

In [49]:
#find the change-of-basis matrix Q making \rho(g) unitary for all g \in G
from sage.matrix.special import diagonal_matrix
from sage.misc.functional import sqrt
def unitary_change_of_basis(SGA,partition,K):
    rho = SGA.specht_module(partition).representation_matrix
    group_size = SGA.group().cardinality()
    P = (1/group_size)*sum(rho(g)*rho(g).conjugate().transpose() for g in SGA.group())
    d, L = P.eigenmatrix_left()
    return L.inverse() * diagonal_matrix([sqrt(K(a)) for a in d.diagonal()]) * L

In [50]:
#define the Fourier coefficient at the representation specht_module
#which is the Specht module corresponding to partition
def hat(f,partition,SGA,K,unitary=False):
    specht_module = SGA.specht_module(partition)
    rho = specht_module.representation_matrix
    if unitary:
        Q = unitary_change_of_basis(SGA,partition,K)
        unitary_factor = specht_module.dimension()/SGA.group().cardinality()
        sqrt_unitary_factor = sqrt(K(unitary_factor))
        return sqrt_unitary_factor*sum(f(g)*Q.inverse()*rho(g)*Q for g in SGA.group())
    else:
        return sum(f(g)*rho(g) for g in SGA.group())

In [51]:
#define the delta function delta_s(t) = {1 if s == t, 0 otherwise}
delta = lambda s: lambda t: 1 if t == s else 0

In [52]:
#for each basis element g \in G compute the Fourier coefficients \hat{\delta_g}(partition) for all partitions
from sage.misc.flatten import flatten
def unitary_dft(SGA):
    K = containing_field(SGA)
    return matrix(K,[flatten([hat(delta(g),partition,SGA,K,unitary=True).list() for partition in Partitions(SGA.group().degree())]) for g in SGA.group()]).transpose()

In [53]:
n = 3

In [54]:
SGA = SymmetricGroupAlgebra(QQ,n)

In [55]:
K = containing_field(SGA); K

Number Field in sqrt3 with defining polynomial x^2 - 3 over its base field

In [56]:
G = SGA.group()

In [57]:
SGA_dft = SGA.dft(); SGA_dft

[   1    1    1    1    1    1]
[   1  1/2   -1 -1/2 -1/2  1/2]
[   0  3/4    0  3/4 -3/4 -3/4]
[   0    1    0   -1    1   -1]
[   1 -1/2    1 -1/2 -1/2 -1/2]
[   1   -1   -1    1    1   -1]

In [58]:
#check if A*A^T == Id. it's not, but the columns are orthonormal
SGA_dft*SGA_dft.transpose()

[  6   0   0   0   0   0]
[  0   3   0   0   0   0]
[  0   0 9/4   0   0   0]
[  0   0   0   4   0   0]
[  0   0   0   0   3   0]
[  0   0   0   0   0   6]

In [59]:
partition = Partitions(SGA.group().degree())[1]; partition

[2, 1]

In [60]:
specht_module = SGA.specht_module(partition)

In [61]:
rho = specht_module.representation_matrix

In [62]:
group_size = SGA.group().cardinality()

In [63]:
P = (1/group_size)*sum(rho(g)*rho(g).conjugate().transpose() for g in SGA.group()); P.base_ring()

Rational Field

In [64]:
Q = unitary_change_of_basis(SGA,partition,K); Q

[-1/6*sqrt2*sqrt3 - 1/2*sqrt2  1/6*sqrt2*sqrt3 - 1/2*sqrt2]
[ 1/6*sqrt2*sqrt3 - 1/2*sqrt2 -1/6*sqrt2*sqrt3 - 1/2*sqrt2]

In [65]:
unitary_factor = specht_module.dimension()/SGA.group().cardinality(); unitary_factor

1/3

In [66]:
K

Number Field in sqrt3 with defining polynomial x^2 - 3 over its base field

In [67]:
G[3]

[2, 3, 1]

In [68]:
U_rho = Q.inverse()*rho(G[3])*Q; U_rho

[      -1/2  1/2*sqrt3]
[-1/2*sqrt3       -1/2]

In [69]:
U_rho*U_rho.conjugate().transpose()

[1 0]
[0 1]

In [70]:
unitary_dft(SGA)

[-1/6*sqrt2*sqrt3 -1/6*sqrt2*sqrt3 -1/6*sqrt2*sqrt3 -1/6*sqrt2*sqrt3 -1/6*sqrt2*sqrt3 -1/6*sqrt2*sqrt3]
[      -1/3*sqrt3                0             -1/2        1/6*sqrt3        1/6*sqrt3              1/2]
[               0       -1/3*sqrt3        1/6*sqrt3             -1/2              1/2        1/6*sqrt3]
[               0       -1/3*sqrt3        1/6*sqrt3              1/2             -1/2        1/6*sqrt3]
[      -1/3*sqrt3                0              1/2        1/6*sqrt3        1/6*sqrt3             -1/2]
[-1/6*sqrt2*sqrt3  1/6*sqrt2*sqrt3  1/6*sqrt2*sqrt3 -1/6*sqrt2*sqrt3 -1/6*sqrt2*sqrt3  1/6*sqrt2*sqrt3]

In [71]:
U_dft = unitary_dft(SGA); U_dft*U_dft.conjugate().transpose()

[1 0 0 0 0 0]
[0 1 0 0 0 0]
[0 0 1 0 0 0]
[0 0 0 1 0 0]
[0 0 0 0 1 0]
[0 0 0 0 0 1]

In [72]:
#check that the DFT is unitary
(U_dft*U_dft.transpose()) == identity_matrix(SGA.group().cardinality())

True

In [73]:
#QUESTION: what are the eigenvalues?
#need to be careful as characteristic polynomial is degree n! over K, so [L:QQ] = [L:K]*[K:QQ] = n!*[K:QQ]
#for n=3, [L:QQ] = n!*[K:QQ] = 6*4 = 24

In [74]:
U_dft.charpoly()

x^6 + (-1/3*sqrt3 - 1/2)*x^5 + ((-1/6*sqrt2 + 1/6)*sqrt3 - 1/3*sqrt2 - 1/3)*x^4 + ((1/3*sqrt2 + 1/3)*sqrt3 + 1/2*sqrt2)*x^3 + ((-1/6*sqrt2 + 1/6)*sqrt3 - 1/3*sqrt2 - 1/3)*x^2 + (-1/3*sqrt3 - 1/2)*x + 1

In [75]:
#ISSUE: the splitting field appears to be high degree, and the coefficients are large
#the defining polynomial is monic with integer coefficients
#since the eigenvalues lie on the unit circle, a result of Kroenecker implies they are roots of unity
if len(U_dft.charpoly().factor()) != U_dft.charpoly().degree():
    L.<a> = U_dft.charpoly().splitting_field(); L
else:
    L = K

In [97]:
L.absolute_degree()

192

In [99]:
roots_defining_poly = L.polynomial().roots(ring=CC);

In [104]:
[abs(root[0]) for root in roots_defining_poly if abs(root[0]) <= 1]

[0.955110617391679, 0.955110617391679]

In [107]:
eigs[0].minpoly()

x^24 + 2*x^23 - 1/2*x^22 - 17/6*x^21 - 215/144*x^20 - 1/6*x^19 + 509/216*x^18 + 11/3*x^17 - 35/1296*x^16 - 139/54*x^15 - 1483/648*x^14 + 7/18*x^13 + 155/54*x^12 + 7/18*x^11 - 1483/648*x^10 - 139/54*x^9 - 35/1296*x^8 + 11/3*x^7 + 509/216*x^6 - 1/6*x^5 - 215/144*x^4 - 17/6*x^3 - 1/2*x^2 + 2*x + 1

In [77]:
#one can factor the polynomial over a splitting field L/K
#but there is no way to express the roots of a quintic in terms of radicals
eigs = matrix(L,U_dft).eigenvalues(extend=False); eigs

TypeError: No compatible natural embeddings found for Number Field in a with defining polynomial x^192 + 192*x^191 + 14112*x^190 + 360144*x^189 - 10547640*x^188 - 759567024*x^187 + 3303157536*x^186 + 1122505191504*x^185 + 5401647864108*x^184 - 1721006003784240*x^183 - 35525503744869888*x^182 + 1677204338167094544*x^181 + 68471564531104940184*x^180 - 810072490769586088560*x^179 - 78750120126358437740064*x^178 - 92202012249342070521456*x^177 + 76961116493830328018951574*x^176 + 1091784078446739644582245008*x^175 - 57016504061931776880623223168*x^174 - 1899974167833213290393577144720*x^173 + 15762506151213242060867303022072*x^172 + 1815943377932309641832033486649840*x^171 + 22487702029300480198395368991239136*x^170 - 924239962930982964793384896135282960*x^169 - 36932060016629518907608609070841454260*x^168 - 112814749564950243986936680722856252560*x^167 + 27434219980661484801871073978391471218304*x^166 + 772271081184566021686911313828834363923888*x^165 - 4033393652946001319989362617087839453296408*x^164 - 750915642289498214016158954544027842546287824*x^163 - 15268782342530559706503992555002990460987394528*x^162 + 217183638890230312661327650531577074540393751856*x^161 + 16796650192224728585809863682492012470700789081713*x^160 + 250244205884900785194962089601484156871664672532336*x^159 - 5632840466188487212443392827310648162082276061755936*x^158 - 304765028649046816652376434440551129354155099401970688*x^157 - 3620723537570756428148608704608579851615806934415229504*x^156 + 109783447610783265532775184938546968206562395346458762240*x^155 + 4860788101318309700224176714162481092697526716777886210304*x^154 + 44830437078274780317912206518239366951955249856233977583104*x^153 - 1903011590385060075087250701230706881685083978730305495904768*x^152 - 69012745531221479293021622476205036104435110016764776106086400*x^151 - 441870188497575180611215024448429425602121752921044621994000384*x^150 + 28987314308785578233778732691051493561883332274453591815134150656*x^149 + 884392712596329292083750086621434634175979859188252677269838594048*x^148 + 3910065868593133005886301112400515725364621820696944477217750941696*x^147 - 383119117793206245440444324165998472752491198305932799070335696633856*x^146 - 10554441955886543113991318654053917152886084803025023647372085389688832*x^145 - 38564651997611303763823576692455857838541490082253234681255427928948736*x^144 + 4419463390359982398448660237316996344554641846876925122268548913089740800*x^143 + 115892554488712638999247710883539848457101457732353407166427599676751478784*x^142 + 432370623715378814062903892848490781590036015231314936986044504525645021184*x^141 - 43758404086249932704956844895726949027719690519329231874350038896281326190592*x^140 - 1118720454391498346645953227242100948104873862534876179103912626138108531834880*x^139 - 4672075543497376005604826977017174342654674138346287605314266335283294735695872*x^138 + 365921116324628217138419710949174109574385077802563821308980511750713404794339328*x^137 + 9267460219720887954454983784616629505845746461557345664425522000098094616061935616*x^136 + 41408630751559817176704070446493601572064640768355164840760260982499958563367026688*x^135 - 2714850654638698131906446963794682627862769232352045323318072416557928523963459174400*x^134 - 66867808283834738705700558097668217131249884335744251470225138697451273111418154516480*x^133 - 242995836360433702072896728527982980813136755774830156640930458400559834509573072355328*x^132 + 20114717275013833454203551281457538751374694898230048885192770940530978371582373222416384*x^131 + 460873938716880614994552879351077158414967066841734666511975340823091168597432169433923584*x^130 + 967315936528353757045049698876609060593591533300156333459871795020321877749540248954601472*x^129 - 165613603609775580088062916902011867187230081304141032414736176995923542297148624715886100480*x^128 - 3857142381853929096919507283954366818972986955399783702703924672830470557039201973475674685440*x^127 - 12322330705301509575681448450942705465718348675887435716644842835519051446449235043671791894528*x^126 + 1455670937099596828525611691813177693808529787423114964966530421949061503231863558920891652898816*x^125 + 39754638599803942993065145412212278636384048229033376246278657682045383770525810564611625625583616*x^124 + 277246290616703011555031354987209303209980836262936305812181347974094087007078295645462522341883904*x^123 - 11193348076232118371824558649264423325541104893967838784172167021153647662710478672502349909232451584*x^122 - 378690909938484630729283153226326839025055246504397378155009653089931701954560248740573757433180061696*x^121 - 4005866793317296074181853482504903840998667093064082584000458845591048763830411680491373010832343433216*x^120 + 57939749072551729273362003896416129318722128476452413786273947686288275725828145763320319568606824235008*x^119 + 2679620427110498300341061185419514718957038998463969501098625274296127476848435767320187617147625416949760*x^118 + 35261325276242683653191571833752828066612763725619012427287203851081436438755683523948900373311674564739072*x^117 - 137498791990149490146804619114756820887938256071964332610590871796746091651213361770700464119933273223725056*x^116 - 12077672177784603654577428942480996827843858766832536655594466597349849899004222711165194063320308123168669696*x^115 - 159728523564119578540134706664349209582290381018350032597748282588048907372416483045711674802158681053332504576*x^114 + 312545293290815717987572387681694160363573982642340204447788742976222716315733670810252934461571621300346028032*x^113 + 28427630663318663135306157119571113707591791642888301528163045807165478553978941995933275298840552537678678065152*x^112 - 102574939591582624438926440277750050721696217908008638185574107069752238302557962444986684151949163515123404374016*x^111 - 15771185942627966588224283020054621912305254352092602053370713624016322143908607788716531441513362007091710898733056*x^110 - 246410615620764769385610218315453117007347691825411361079557557683417685064736614843261152977999445393894954667868160*x^109 + 2621239120722324991680466578946924126760590967844687610759954257346899933847460661751967851433238213321485854672158720*x^108 + 215222562550577574466310284458530230764816859760599822023193061548147135553578270942059717458581882337290483545743032320*x^107 + 5461774897553504683655505025865295357921872911910077546799445007373790859438169926240952761775891579776811950768876683264*x^106 + 66377271669369222317628794735204515616510268540764850868989557796993727059517446526454801930641960093059696614779071234048*x^105 - 526930280684859330912788179409457304623624764511899359364375250206254278137527581808213598734615516160449749236510172905472*x^104 - 45897451038253393545389448792105535889236791039450912619438719788340618339140501847474433749113492983014255830941613665812480*x^103 - 1132374333776187760439833705912974420158859542556536355259535927321450995594879186796937206264830349426960113501822667068538880*x^102 - 14179482977301760610561184728756395454731710488550198799926459204452697605900920724192346857118963504627266439446678857102393344*x^101 + 39286610967374905495251047563031661906584927709621518011521599702790664349080944322343439493123452620280389482980388281362939904*x^100 + 6652715507896467311474595030038355894290366207462478856752904309072029514198013942532667270302303825281512889689827905444285251584*x^99 + 177337127508034685490539166600348236424026552505957410027144620177035570694573617743458245665127531040434282789041038266949101944832*x^98 + 2615977132398190576899311791105313035048701323440082745739465942411507924737835445440672346793365216428250097647476575828496789536768*x^97 + 10236750716431974206219581649565649309971544501670121584488997322600894390545808417230651384459222076427257235108328861026452598947840*x^96 - 625089615421444570552718589457319222797697606479389446408530616782777226337908892793829984688269764667422606279063730297410644275625984*x^95 - 20701277518257242840478953891657087069199212513615413360378272461979388979160837840084580605351242840663237766363352109071639757665075200*x^94 - 360702270525240764669334632483084615963441422193421153367520157877511835818942133936823373605731127670453900115705057366625224885490679808*x^93 - 3123927187609268695109408247789472902440092958791810501574871304472805526021590156735277332480587712267702926398982269015791151283171229696*x^92 + 30863833790180792784164411941477900538135301774863123240915704791921863627413840849076334174658109609490867672371924291005687357178715832320*x^91 + 1843869610572259326923106379292535277776172248760615971494028789140941547395667506161531484587841939649749707634856345941110153275788662669312*x^90 + 40685250629503362955871568601909050790978293826132839721017641480062712202991834853371835158895172235594912863458015964939023583296295920467968*x^89 + 537932063200382795358583176026830203343236006797178863795197357882943307857662176515495499208256361577323578497892037876645386624706644967161856*x^88 + 2329626320946834745008846498117489185681575148387275245732009889681121444372373653745730189373010620474057637380622702187885948135233080675794944*x^87 - 92375875793893506890759727178086592248576047813154984608632492593987833204110806058418101812396580129726320607837600641650690987011833510607454208*x^86 - 3023395212681871172797816303463284936288113391263720076106453413690571570807170097072022173858704864863161630462421707534930614636391218918553812992*x^85 - 52014708824858562679051756437938666091508931290559113181172494191763518917676883410874534456341164882125974940579472798023983489548869226295543726080*x^84 - 517167569855608091741949816051450957754475640031105380318839070214339640370207889674452269178637306660251856533168258989054195589672340819190801760256*x^83 + 380106657541445846019747635025558921035343349265588619778451633297613536520216822395069555218548475285691229011903288984582653798823801408134513164288*x^82 + 139929133784384676871811634294881208635101027878284473713978531715370913107143352453142488194327401879959593651947527029530957703689498761680294797901824*x^81 + 3428646408233642094278227933783137435850939810103243227277166177882189072666735256001207453354277277007308537191302913216049302607570593457474519726817280*x^80 + 52439702480999832722204912652939493200176802106010056128755754817652646104961899915728878558838639524723344931783394751949966064152441403301479568105275392*x^79 + 508488799057302184037466877488975464531917446735151453855195612921876826069969243986061025787916506447531334574781755248059787633467371401261531270561660928*x^78 + 846469413370550615600078269258738215284538459519651055102853934108410690079892145188744539251288167569664358584907816733631686307778869951415723754981949440*x^77 - 84391238405009278894021244789326755950337745690259076318735400570666694811073425421251784788703304169416529239397160131777464814162321246399440219514825867264*x^76 - 2072935373725338521080991329358247727870845377208986002390887845062464817400130063913838657837888340358854838590100659092712149823241661650515523158499343204352*x^75 - 29994135965756233219381742711512817260946417000903033929759716597742176523979032401570942608918093051735656401898241858555757986423312475571671347220534188310528*x^74 - 271392706843770008361781619108418282800618357066702145533247618223663003338776780975446908461021030066790789439910072356423422848866245760031836088841840497786880*x^73 - 347791871411408243952815838272402863213558986370837723781586662560641826389170001332415731782384491987300902364055059241871473775549445388995289974268900537270272*x^72 + 42648611804475508273912852298648490591003057532369768410269571674735759600277634485583019918320397898275080188085784652288085607087218997311739333188846529368031232*x^71 + 985435880969901017613420821895223855851814423267159679525201727254202231807559660296139012160732831099516288925846583463745107337199986160121821931193010610541428736*x^70 + 13709325052561502252256118940203271014642665310017992434649250842106310854668372949679589109700805922765293817587765627041780550007576915908285749423752665686301736960*x^69 + 129498884171533128805687096902639477608323754343912077605500924808513639423322810299065477000442332427780928761227466364075086885825198499940897064141885446512361603072*x^68 + 636260541583585413660009452206937535673819003125986012567242440101732786366972440635519511901542932565412954270037234614911186824349434100674158554400891654235198849024*x^67 - 4401339252731981334579872285702613761199842098356777166524770888172830356299999912412120434459999013304619579423640888334060851571599483803098887958588738690007976378368*x^66 - 146837084860523248702898158731119711004112255971374527589708082961343911596513430010694091578277021310641827583660298191074145272976329531486948199068409394117897091022848*x^65 - 1837812187793538472269541836970828832217229790357589744226931035559178029734160462417524970854712925879611480377610250107476420667776369486963422444320664845061457717493760*x^64 - 11966280952398868923320216615784396379532184888551262503895731377329934183053475626977322246024755262601944031039335675927205579928229227134163390871669326585662320697933824*x^63 + 19500768892843156025415364083792115754387098927597726149910591182304648614826084909016209815666221403578313288462065850831457604050806843916244334218726598918711933658988544*x^62 + 1700835515874997485034041929992239283957749240175057075271998059116342594351176356031171478068997572375147115705058281379270887267801041852061412408370600109775260265027207168*x^61 + 29922155806576460215932427068390265129253137014920348376553353783130584125941315217411675580436593450059015241455529078648457548920498067600450945427380395637363927412855799808*x^60 + 441497847091232916275759541356120226281558514367258515993066098527096793296805781284822887746498008147163225366712750443183823236048549359402991601449726196489435128802112962560*x^59 + 6816340778982026327582714717218550281429514736404916274414733070972406113950661127865350696671195784553128308913984395533265809293525692118262750184046827234002429209861888671744*x^58 + 110354637126028550399347673830277998901198676329230083063067350243262100853410415334587970781125180983145962400764206344692086779247264058802886218160474068938408845229202190893056*x^57 + 1701241069155978400677696489150970934500899100937288799190275953669132351343590397394493733629613780049595160310723355788384668768150095064779475590495269332750270724267520198443008*x^56 + 23202543098244645539426896216589811194560233443116258031466122077572439168344115802073082399516449257524953891164985561561491386129418047024425045977604767597404322610170643106234368*x^55 + 275555374968290143460588174901747986942266516233732762703789814861682382389714705649526910266086197351700896169284745419692836320905106608836268494797694883380730104839437461487616000*x^54 + 2939443353019603753437539495707712998373087172748237624032403598190910488402262582724483572637273584055245255238031696195925480215221349263336210783077046434060551454192335947399430144*x^53 + 30072674792013234583447218683221438557452687048867689900414566840031946688138057482945064443496195387632509813800380263705410371383607721657739230203977874568411444006823160784265150464*x^52 + 319034897674870058636906644502332635529957791587866159830442799313018149408171808146726080827936963717692467224371201816337697704741842313331177697286662449861578078474765991947609833472*x^51 + 3622136441862152212889373549020459352144563232914440498315739441831690597590429280111780913551439605500410200727576931586724234000958297531810973462801437530342711059731945808647296122880*x^50 + 41580130994694480744504612942452141248565150124164618185906884193887062306515080041051487072921897627698709580574362660454844986025940294206191213081672932598221257832225210837719500980224*x^49 + 440684456274810152583395637171205061227133551187974680586313585956610543719836066317814131168018671540896934174506883626235139825426410832330319991732008875401525897834351186395709688512512*x^48 + 4063437237501005734925160663478180765517179057789895244677150721604280582382430902064400197075186937454236098011090535963468495487590439613876752900487754245901825943568173752595166240178176*x^47 + 32248407768614026535313674691606895417683379219644512593393930536377725375300672927953820705098461956281768671877577570508275227419230388296334223754309667755694168607322412644892002756853760*x^46 + 232422020740956243603494484978881043618679613202966381443292513094808864335088817293075966170003402095223386262758323137646076028552359839401096793954629572771854988650956628267558614119481344*x^45 + 1764108310584530091268744812374267047110763372822624633053352651473430398600467027528806649432145037643548044926309420659511449996376330136810068022274754378942173592730071701340137216473563136*x^44 + 16190615495632225968481067955895682062867182023980239378787430070631979246579942554176861746632807241264280243764729709867878056925594029348369419316110209149188935751629354966535676806240927744*x^43 + 164591004975896488924492168330891930604605092965408602049840669086474383994132606348521247636792362849197980075956049109665985214787989088919261044406715714749812051348845360504759376274780061696*x^42 + 1547808049647742622177439928600414280585960750257522153892045615944413400597651782753213277842790259798123299932198888463314473483834585058738449252586662062330401783982224189340668139121726717952*x^41 + 12241452463144162790599739140884460025351691531780414916481322975991809054203610525477621349576308654968108407901490689571702740960341018694605725451633406470692745014485181699929728380509368614912*x^40 + 79057812552683930643619508764440517939711697878411708164415398033600048390105616677938084611981237532088757321178334182354527223876543080661113341817827282390790951739719170065134365730688458555392*x^39 + 422179669934493963226713027451698081598134864145948199966133563578180555696355212787793002160183505263362476150880853309828503565111339949157935526619696839501954190794761361813499355241420207161344*x^38 + 2136171686967383171307821094338728524730814678967946761292237148783890807464215163375751202972400967058575462731216164642007913807711169916071953475489163065368302129160952494699880994401392621780992*x^37 + 14942611685613516953850187964887713635071833025862934003969598692825569204399580429313318671109917813565378302733439931835759352517323510908582654661200014947713739267613140312339313482649725256597504*x^36 + 152908909543969706773797073549239802834766751181770294235950256160002337088706423747365946309630478100113364406250643814753112951903169102463491105899003675990876036533668930738086004676616480454868992*x^35 + 1527011564563115874316661609273862535796894336290112781881252114946802323316543787336941655924199917511096407402613940629488854390320425687505062417507165548599836614098426023952277621031373391760719872*x^34 + 12109597729242544621935028188789519446462130711595128152300412953261089199931078543275149161104112580853479672417390570271995391637988564426576856633571478732036840050658533648295502183170035099931508736*x^33 + 69433258839018385554407672056877602704688446921691168718557244379002511596929079204921720480511746809627284597254802781676427218573475299883092619675559840599101579816933510607514949912774809714522324992*x^32 + 214356038878817416681166342228015713837309084672955190884564874008985607910365777848959812508870494729753446798943506960035043691843547261095480785770454119482348973924479102905166571701477573996616613888*x^31 - 743638351907128978899739750214764885330859635153968828583688685559051806131231531840391875990866533988661140183389922914083952661350168018789104301934895590158739121871533199593240778717536923171059400704*x^30 - 15664017347651288599045083765275775023443113760513870693190778186275257388498507416295982435950616648621162367033513584813710684273951015640280785044657283429575289524752729289221103341231131058719871205376*x^29 - 113433756605470436916326929196446851260871509221359714610434021292549828552501824618810507437348257104514490500772205626800703728498216424214853993978193842188853686599584790584485152191171236058158417838080*x^28 - 428470150505286328656841387306325120280002269589777268442320624716651148694825439271036549793294604017331407773727862848602401551401236660713095165490826544490959138068237185637285806232989229800945870700544*x^27 - 102078122169800269618013269412203491867080275429555824346194367478646194678751649570516617519121656750716892973664093284912163584432099815126118776482695855468533540952484477362153870006297474951464905342976*x^26 + 6329069643035829377570052052354908182051815509996164312370569014120930694779440405792634426848014516405826635142487245628918034608908659765256457426068569193208385939190979422185190951301025868342487890788352*x^25 - 24965501600283905394626732547279235424212197901000824230324548627451655879443634103461807495757129742509443678578471160000502837990816076249357706032794721098815902397862923755169141402086358375502764167921664*x^24 - 1100783258303647629379191349954097193541176370091869522000284128262951577766392328743134795351065995890721820833060495437384594810353435210574817899465344202376939814313573262915650899833975582687154594220343296*x^23 - 13198565030880884536411491072626088344556272167452805238510259477270946641142980903938504653060325132370419860232170870705482221106131911141616839729479404852240040690357378623771165103304084398634287414286221312*x^22 - 103732392357914368355119295429881872682839374186782481559113110744676039401209456183299270418555172321103789904176494471929040222601660737199230939217793299866459602145523978724074504681007778188402100077865205760*x^21 - 586797324448748412246783515249295999547682512887345008902600212432279261015551201945354177567589156264816751987422120172958686971865124176294386722127410588355215931212717960101331461909799549174189956633624313856*x^20 - 2076537207821481915879070098306924173318394642712174663990598157789769134948464270146062949920322934613179506296850271543606564327412724415562857787366746604814357821304259232848099602740931697268630791169452802048*x^19 + 1561981190969558956674023123865049775842955740863294855964338894981986426092904906011060540298106420750316430514085611267593535619522711058867845678130728925463336975067237474556910632299809444757160843042667626496*x^18 + 101080583417986036369685643083850508870528761212199894788525066156337140631524572216850134297047785689575597581812293029847375396194563700089843928556913450340946742114445986359893581239967720961377403828136176517120*x^17 + 1038389570699682880855983206925468277376079746193103963268236824771161304116307311142821515780515620154838452948962562187661615521149165165217864518646334753368503436329115892263307881022840245177366129215533897220096*x^16 + 7452896476318657162115049555507437793227387839220509348536723812888782183973266446534315101642920433217780227404275006088375628485059959697952719375076133941640144357204102000014697266374493828851631576604093995548672*x^15 + 43291358578506420984230953545360132412771726239190773971292212924379353557598024010844119059927701949528538382894117128299148015089539451385565762264896927991456821805072043525485924533907205739918191049643677985013760*x^14 + 213103102230311916079129644105626750439684262380069351255335432993745831586226507408035530769406293245065749251094112582597641979437810200193327422126346260361450422169823678137274758114074299856701018124601381298896896*x^13 + 905144944660939354570297044891879753146700085377614129340769482910246280423038180182890594929653257035246889998106278169610139236248680457511133504693109526342306638960931731856283687269894705145435913486576493338296320*x^12 + 3341064176388551388200268260464383650377188222927760117688192410705435208588060148916557896636162679851287440747855172991333341153589961146461769105879620085954851991307762874774153727014443401828275996283763772115386368*x^11 + 10738403841787441162430373350673760141829764492716343295721878420246662896204995942299697458727472805673692865896118749256829719431852802365901277557692470628019355996134524969728069030938145758000693438300899991793696768*x^10 + 30004057778835046511775874246067231769671580959090317458492341454557145012446860102441669873679044743476609483686666699078953670918504915754569956886652243631464870137127923794849206363033759788158716154954257214260379648*x^9 + 72583999170156307198847932768400093856798148886117189393635680511308596566592247437229114000065116070811784738784081523740852185253268827648127516410141747736348964180224660112116234238419073032596754025671911318973579264*x^8 + 151190577069963593289641440183081349992910680939928334735743653598665804232790338059475611296735723144236773806930579471589973975413263568658298250826723339839962769682518363190005099149210269174828783780586859136091684864*x^7 + 268828047429317602730072878123388456791248041706488437871414932131005227888676429895474943326947817335345257180103455386095868482653706794912200321631810228239063576936450726546713802214115174160520134317282480074914791424*x^6 + 401952953638897968415314787148813527831141758853316499665513276960559917470064900901415719170382814566938551434222366305691143271177401819101123179875374752899981087490827137663764836641586496108265629463928993225858088960*x^5 + 500186269565093084615595067135276429911508825467031268487146655797824268201996429525854725240711703620348276199921701491958421611662538085990529537045573859126985202990349047412035899395942596432757096134856828474913456128*x^4 + 493447881194072560617202378947956788005646809644760620475255675524590837226837450179659475163765540337424612767496367842177483963538349810100498800181427893904311758963441287005208364476552261468385752043203573179521957888*x^3 + 388116118168118541259232484380347196094708992884098893111872584468319777135621974783092629668054489224129878163554776792891232177840246342384859631776128690095482895527947770770873521575592701192934175173960340582915112960*x^2 + 200760841877708540720300655663469023462624636485948933111025429342889732144730232885509607414745274051079850692020432101291790455272393598244920916341361338823209162025364968359312811423001995211418681589269344777035317248*x + 77894844475440561834328420677199820958251534784016540614070057728553043785264663728841929190352787260240770152901619928879662956310107414933121426378653485591871664083075162894063837522478664498887306217799056867823976448 and Number Field in sqrt3 with defining polynomial x^2 - 3 over its base field

In [ ]:
rational_approx_args = [(arg(eig)/(2*pi)).n(100).nearby_rational(max_denominator=100_000_000_000_000_000_000_000) for eig in eigs]; rational_approx_args

In [ ]:
#galois_group() appears to be the absolute version
#NOTE: for a splitting field L, we should have [L:K] = |Gal(L/K)|
if L != L.algebraic_closure():
    L_G = L.galois_group()

In [ ]:
#n=3: two real, two complex
#n=4: all complex
#the magnitude is not 1, they're closely grouped around 2 or 3

In [ ]:
SGA_eigs = SGA_dft.eigenvalues(); SGA_eigs

In [ ]:
[abs(eig) for eig in SGA_eigs]

In [ ]:
#note that the singluar values are the square roots of the diagonal entries of the Gram matrix
print(SymmetricGroup(n).algebra(CDF).dft().SVD()[1].numpy().diagonal())
print(sqrt((SGA_dft*SGA_dft.transpose()).numpy().diagonal()))